# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectAgency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='data_type',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='ip',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='port',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='position_X',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='position_Y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='related_data',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='share_pin',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='token',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
