# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConnectAgency', '0002_auto_20170510_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='public_key',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
