# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_phone', models.CharField(max_length=50)),
                ('publish_time', models.DateTimeField()),
                ('token', models.CharField(max_length=50, null=True)),
                ('share_pin', models.IntegerField()),
                ('position_X', models.FloatField()),
                ('position_Y', models.FloatField()),
                ('data_type', models.IntegerField(null=True)),
                ('is_active', models.BooleanField()),
                ('related_data', models.CharField(max_length=5000, null=True)),
                ('ip', models.CharField(max_length=30, null=True)),
                ('port', models.IntegerField(null=True)),
                ('public_key', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
