# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate', '0002_auto_20170518_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='ip_direct',
        ),
        migrations.AddField(
            model_name='transfer',
            name='installation_origin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='installation_target',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
