# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinate', '0003_auto_20170522_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='data_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
